server:
  port: ${PORT:8080}

spring:
  datasource:
    url: "jdbc:sqlite:/tmp/example_db.sqlite"
    driver-class-name: org.sqlite.JDBC
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/static/

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      table-underline: true

logging:
  level:
    com.example.campuspetfoster: INFO
