server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${MYSQL_PUBLIC_URL:jdbc:mysql://reseau.proxy.rlwy.net:32490/railway}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:FombvUtVVkscGEehlunozfUGlAOFoher}
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/static/

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      table-underline: true

logging:
  level:
    com.example.campuspetfoster: INFO
